server:
  port: 8083

spring:
  application:
    name: my-bank-cash-app
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${bank.keycloak-url}/protocol/openid-connect/certs
      client:
        registration:
          cash-app:
            provider: keycloak
            client-id: cash-app
            client-secret: ${CASH.SECRET}
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            user-name-attribute: preferred_username
            authorization-uri: "http://localhost:80/auth/realms/bank-realm/protocol/openid-connect/auth"
            token-uri: "${bank.keycloak-url}/protocol/openid-connect/token"
            user-info-uri: "${bank.keycloak-url}/protocol/openid-connect/userinfo"
            jwk-set-uri: "${bank.keycloak-url}/protocol/openid-connect/certs"
  kafka:
    bootstrap-servers: ${KAFKA.URL:kafka-broker-0.kafka-headless.default.svc.cluster.local:9092}
    producer:
      acks: 1
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    template:
      observation-enabled: true
  reactor:
    context-propagation: auto

management:
  endpoints:
    web:
      exposure:
        include: "*"
  zipkin:
    tracing:
      endpoint: ${ZIPKIN.URL:http://localhost:9411/api/v2/spans}
  tracing:
    sampling:
      probability: 1
    enabled: true

bank:
  accounts-service:
    base-url: "${ACCOUNT.URL:http://localhost:8083}"
  keycloak-url: "${KEYCLOAK.URL:http://localhost:8080/realms/bank-realm}"
  notification-url: "${NOTIFICATION.URL:http://localhost:8086}"


logging:
  level:
    root: INFO


