server:
  port: 8086

spring:
  application:
    name: my-bank-notification-app
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "${bank.keycloak-url}/protocol/openid-connect/certs"
  cloud:
    consul:
      host: "${CONSUL.HOST:localhost}"
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: INFO
bank:
  keycloak-url: "${KEYCLOAK.URL:http://localhost:8080/realms/bank-realm}"

