server:
  port: 8086

spring:
  application:
    name: my-bank-notification-app
  kafka:
    bootstrap-servers: ${KAFKA.URL:kafka-broker-0.kafka-headless.default.svc.cluster.local:9092}
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      observation-enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  zipkin:
    tracing:
      endpoint: ${ZIPKIN.URL:http://localhost:9411/api/v2/spans}
  tracing:
    sampling:
      probability: 1

logging:
  level:
    root: INFO


