apiVersion: v1
kind: ConfigMap
metadata:
  name: transfer-configmap  # Имя ConfigMap будет комбинироваться с именем релиза
data:
  KEYCLOAK.URL: {{ tpl .Values.service_url.keycloak_url . | quote}}
  KAFKA.URL: {{ tpl .Values.service_url.kafka_url . | quote}}
  TRANSFER.SECRET: {{ .Values.transfer_secret | quote}}
  ACCOUNT.URL: {{ tpl .Values.service_url.account_url . | quote}}