server:
  port: 8085

spring:
  application:
    name: my-bank-transfer-app
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${bank.keycloak-url}/protocol/openid-connect/certs
      client:
        registration:
          transfer-app:
            provider: keycloak
            client-id: transfer-app
            client-secret: ${TRANSFER.SECRET}
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            user-name-attribute: preferred_username
            authorization-uri: "http://localhost:80/auth/realms/bank-realm/protocol/openid-connect/auth"
            token-uri: "${bank.keycloak-url}/protocol/openid-connect/token"
            user-info-uri: "${bank.keycloak-url}/protocol/openid-connect/userinfo"
            jwk-set-uri: "${bank.keycloak-url}/protocol/openid-connect/certs"


management:
  endpoints:
    web:
      exposure:
        include: "*"

bank:
  accounts-service:
    base-url: "${ACCOUNT.URL:http://localhost:8083}"
  keycloak-url: "${KEYCLOAK.URL:http://localhost:8080/realms/bank-realm}"
  notification-url: "${NOTIFICATION.URL:http://localhost:8086}"

logging:
  level:
    root: INFO