spring.application.name=my-bank-liquibase


spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:6432/market1}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:v0IZuTHY0Y}

management.endpoints.web.exposure.include=*

spring.liquibase.default-schema=account_service

spring.main.allow-bean-definition-overriding=true