spring.application.name=my-bank-account-app

server.port=8082

spring.r2dbc.url=${DATABASE_URL:r2dbc:postgresql://account-chart1-account-db:5432/market1}
spring.r2dbc.username=${DATABASE_USERNAME:postgres}
spring.r2dbc.password=${DATABASE_PASSWORD:v0IZuTHY0Y}
spring.r2dbc.pool.enabled=true
spring.r2dbc.pool.initial-size=10
spring.r2dbc.pool.max-size=50
spring.r2dbc.pool.max-idle-time=30s
spring.r2dbc.pool.max-life-time=10m
spring.r2dbc.pool.validation-query=SELECT 1

spring.sql.init.mode=always

management.endpoints.web.exposure.include=*

logging.level.org.springframework.security=TRACE

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${bank.keycloak-url}/protocol/openid-connect/certs

spring.security.oauth2.client.provider.keycloak.authorization-uri=${bank.keycloak-url}/protocol/openid-connect/auth
spring.security.oauth2.client.provider.keycloak.token-uri=${bank.keycloak-url}/protocol/openid-connect/token
spring.security.oauth2.client.provider.keycloak.jwk-set-uri=${bank.keycloak-url}/protocol/openid-connect/certs
spring.security.oauth2.client.provider.keycloak.user-info-uri=${bank.keycloak-url}/protocol/openid-connect/userinfo
spring.security.oauth2.client.registration.account-app.authorization-grant-type=client_credentials
spring.security.oauth2.client.registration.account-app.provider=keycloak
spring.security.oauth2.client.registration.account-app.client-id=account-app
spring.security.oauth2.client.registration.account-app.client-secret=${ACCOUNT.SECRET}
spring.security.oauth2.client.registration.account-app.scope=openid

bank.keycloak-url=${KEYCLOAK.URL:http://localhost:8080/realms/bank-realm}
bank.notification=${NOTIFICATION.URL}

