spring.application.name=my-bank-account-app

server.port=8082

spring.r2dbc.url=${DATASOURCE.URL:r2dbc:postgresql://localhost:6432/market}
spring.r2dbc.username=user
spring.r2dbc.password=user
spring.r2dbc.pool.enabled=true
spring.r2dbc.pool.initial-size=10
spring.r2dbc.pool.max-size=50
spring.r2dbc.pool.max-idle-time=30s
spring.r2dbc.pool.max-life-time=10m
spring.r2dbc.pool.validation-query=SELECT 1

spring.sql.init.mode=always

management.endpoints.web.exposure.include=*

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${bank.keycloak-url}/protocol/openid-connect/certs

logging.level.org.springframework.security=trace

spring.security.oauth2.client.provider.keycloak.authorization-uri=http://bank-keycloak:8080/realms/bank-realm/protocol/openid-connect/auth
spring.security.oauth2.client.provider.keycloak.token-uri=http://bank-keycloak:8080/realms/bank-realm/protocol/openid-connect/token
spring.security.oauth2.client.provider.keycloak.jwk-set-uri=http://bank-keycloak:8080/realms/bank-realm/protocol/openid-connect/certs
spring.security.oauth2.client.provider.keycloak.user-info-uri=http://bank-keycloak:8080/realms/bank-realm/protocol/openid-connect/userinfo
spring.security.oauth2.client.registration.account-app.authorization-grant-type=client_credentials
spring.security.oauth2.client.registration.account-app.provider=keycloak
spring.security.oauth2.client.registration.account-app.client-id=account-app
spring.security.oauth2.client.registration.account-app.client-secret=A8U5u54LT3m9Besj3SV39L2E6iBh4lkU
spring.security.oauth2.client.registration.account-app.scope=openid

spring.cloud.consul.host=${CONSUL.HOST:localhost}

bank.keycloak-url=${KEYCLOAK.URL:http://localhost:8080/realms/bank-realm}

bank.notification=${NOTIFICATION.URL}
