apiVersion: v2
name: account-chart
description: Umbrella chart for Customer and Order microservices
type: application
version: 0.1.1
appVersion: "1.0.1"

dependencies:
  - name: postgresql
    version: "18.7.8" # Using a specific known stable version from Bitnami history
    repository: "https://charts.bitnami.com/bitnami"
    alias: account-db # Alias to distinguish this instance
    condition: account-db.enabled

  - name: account-app
    version: 0.1.0
    repository: "file://./charts/account-app"
    alias: account-app
    condition: account-app.enabled

  - name: front-app
    version: 0.1.0
    repository: "file://./charts/front-app"
    alias: front-app
    condition: front-app.enabled

  - name: keycloakx
    version: 7.2.2
    repository: https://codecentric.github.io/helm-charts
    alias: keycloak-app
    condition: keycloak-app.enabled

  - name: gateway-app
    version: 0.1.0
    repository: "file://./charts/gateway-app"
    alias: gateway-app
    condition: gateway-app.enabled

  - name: cash-app
    version: 0.1.0
    repository: "file://./charts/cash-app"
    alias: cash-app
    condition: cash-app.enabled

  - name: notification-app
    version: 0.1.0
    repository: "file://./charts/notification-app"
    alias: notification-app
    condition: notification-app.enabled

  - name: transfer-app
    version: 0.1.0
    repository: "file://./charts/transfer-app"
    alias: transfer-app
    condition: transfer-app.enabled

  - name: kafka
    version: 18.0.1
    repository: https://helm-charts.itboon.top/kafka/
    alias: kafka-app
    condition: kafka-app.enabled

  - name: zipkin
    version: 0.5.0
    repository: https://zipkin.io/zipkin-helm
    alias: zipkin-app
    condition: zipkin-app.enable

  - name: prometheus
    version: 29.27.0
    repository: https://prometheus-community.github.io/helm-charts
    alias: prometheus-app
    condition: prometheus-app.enable