
# Configuration for the customer-db (PostgreSQL dependency)
# Values here are prefixed according to the Bitnami PostgreSQL chart's structure
# Check the Bitnami chart's values.yaml for all available options
account-db:
  enabled: true
  # Override values from the official postgresql chart
  auth:
    database: market1
    username: user1

    postgresPassword: "v0IZuTHY0Y"
    password: "v0IZuTHY0Y"
    user1Password: "v0IZuTHY0Y"

  primary:
    persistence:
      enabled: true
      size: 1Gi # Small size for example
account-app:
  enabled: true
  hooks:
    myHook:
      url: jdbc:postgresql://{{ .Release.Name }}-account-db:5432/market1
      username: user1
      password: v0IZuTHY0Y
  image:
    repository: my-bank-account
    pullPolicy: IfNotPresent
    tag: "1.3.1"
  database:
    url: r2dbc:postgresql://{{ .Release.Name }}-account-db:5432/market1
    username: user1
    password: v0IZuTHY0Y
  account_secret: A8U5u54LT3m9Besj3SV39L2E6iBh4lkU
  service_url:
    zipkin_url: http://{{ .Release.Name }}-zipkin-app:9411/api/v2/spans
    kafka_url: http://{{ .Release.Name }}-kafka-app-broker:9092
    keycloak_url: http://{{ .Release.Name }}-keycloak-app-http:80/auth/realms/bank-realm
  envFrom:
    - configMapRef:
        name: my-configmap

keycloak-app:
  enabled: true
# Предварительно надо выполнить команду:
# kubectl create secret generic realm-secret --from-file=realm-export.json
  command:
    - "/opt/keycloak/bin/kc.sh"
    - "start"
    - "--http-port=8080"
    - "--hostname-strict=false"
    - "--import-realm"
  extraVolumes: |
    - name: realm-secret
      secret:
        secretName: realm-secret
  extraVolumeMounts: |
    - name: realm-secret
      mountPath: "/opt/keycloak/data/import/"
      readOnly: true
  extraEnv: |
    - name: KEYCLOAK_ADMIN
      value: admin
    - name: KEYCLOAK_ADMIN_PASSWORD
      value: admin    
    - name: JAVA_OPTS_APPEND
      value: >-
        -Djgroups.dns.query={{ include "keycloak.fullname" . }}-headless
  service:
    type: LoadBalancer
    port: 8080

front-app:
  enabled: true
  image:
    repository: my-bank-front
    pullPolicy: IfNotPresent
    tag: "1.3.1"
  service_url:
    zipkin_url: http://{{ .Release.Name }}-zipkin-app:9411/api/v2/spans
    gateway_host: http://{{ .Release.Name }}-gateway-app:8081
    keycloak_url: http://{{ .Release.Name }}-keycloak-app-http:80/auth/realms/bank-realm
  envFrom:
    - configMapRef:
        name: front-configmap
  service:
    type: LoadBalancer
    port: 8084

gateway-app:
  enabled: true
  image:
    repository: my-bank-gateway
    pullPolicy: IfNotPresent
    tag: "1.3.1"
  service_url:
    zipkin_url: http://{{ .Release.Name }}-zipkin-app:9411/api/v2/spans
    keycloak_url: http://{{ .Release.Name }}-keycloak-app-http:80/auth/realms/bank-realm
    account_url: http://{{ .Release.Name }}-account-app:8082
    cash_url: http://{{ .Release.Name }}-cash-app:8083
    transfer_url: http://{{ .Release.Name }}-transfer-app:8085
  envFrom:
    - configMapRef:
        name: gateway-configmap

cash-app:
  enabled: true
  image:
    repository: my-bank-cash
    pullPolicy: IfNotPresent
    tag: "1.3.1"
  service_url:
    keycloak_url: http://{{ .Release.Name }}-keycloak-app-http:80/auth/realms/bank-realm
    account_url: http://{{ .Release.Name }}-account-app:8082
    kafka_url: http://{{ .Release.Name }}-kafka-app-broker:9092
    zipkin_url: http://{{ .Release.Name }}-zipkin-app:9411/api/v2/spans
  cash_secret: r49jp06vuDWQrAYs1fp9baivXlYOBYUz
  envFrom:
    - configMapRef:
        name: cash-configmap

transfer-app:
  enabled: true
  image:
    repository: my-bank-transfer
    pullPolicy: IfNotPresent
    tag: "1.3.1"
  service_url:
    keycloak_url: http://{{ .Release.Name }}-keycloak-app-http:80/auth/realms/bank-realm
    account_url: http://{{ .Release.Name }}-account-app:8082
    kafka_url: http://{{ .Release.Name }}-kafka-app-broker:9092
    zipkin_url: http://{{ .Release.Name }}-zipkin-app:9411/api/v2/spans
  transfer_secret: dudm1HJ7u6BtZpOiMJ2XImsrF1mYmTI0
  envFrom:
    - configMapRef:
        name: transfer-configmap

notification-app:
  enabled: true
  image:
    repository: my-bank-notification
    pullPolicy: IfNotPresent
    tag: "1.3.1"
  service_url:
    zipkin_url: http://{{ .Release.Name }}-zipkin-app:9411/api/v2/spans
    kafka_url: http://{{ .Release.Name }}-kafka-app-broker:9092
  envFrom:
    - configMapRef:
        name: notification-configmap

kafka-app:
  enable: true

zipkin-app:
  enable: true
  service:
    type: LoadBalancer
    port: 9411

prometheus-app:
  alertmanager:
    enabled: false
  kube-state-metrics:
    enabled: false
  prometheus-node-exporter:
    enabled: false
  prometheus-pushgateway:
    enabled: false

  extraScrapeConfigs: |
    - job_name: 'account-service'
      metrics_path: /actuator/prometheus
      static_configs:
        - targets: ['{{ .Release.Name }}-account-app:8082']
    - job_name: 'cash-service'
      metrics_path: /actuator/prometheus
      static_configs:
        - targets: ['{{ .Release.Name }}-cash-app:8083']
    - job_name: 'transfer-service'
      metrics_path: /actuator/prometheus
      static_configs:
        - targets: ['{{ .Release.Name }}-transfer-app:8085']
  serverFiles:
  ## Alerts configuration
  ## Ref: https://prometheus.io/docs/prometheus/latest/configuration/alerting_rules/
    alerting_rules.yml:
      groups:
        - name: user_error.rules
          rules:
            - alert: ManyErrorCash
              expr: 'sum(rate(error_cash_service_total[5m])) > 0.01'
              labels:
                severity: warning
              annotations:
                summary: "Ошибки при снятии денег со счета"
                description: "Количество ошибок при снятии денег превысило 5 за 5 минут"
            - alert: ManyErrorTransfer
              expr: 'sum(rate(error_transfer_service_total[5m])) > 0.01'
              labels:
                severity: warning
              annotations:
                summary: "Ошибки при перевода денег со счета"
                description: "Количество ошибок при переводе денег превысило 5 за 5 минут"

grafana-app:
  adminPassword: admin
  serverFiles:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: http://{{ .Release.Name }}-prometheus-app-server:9090
          access: proxy
          isDefault: true

fluent-app:
  image:
    repository: docker.io/fluent/fluent-bit
    tag: 5.1.1
  config:
    outputs: |
      [OUTPUT]
          Name http
          Match *
          Host {{ .Release.Name }}-logstash-app-headless
          Port 5044
          Format json          
  
logstash-app:
  image: "docker.elastic.co/logstash/logstash-oss"


  logstashPipeline:
    logstash.conf: |
      input {
        http {
          port => 5044          
        }
      }
      filter {
        grok {
          match => { "log" => ["%{TIMESTAMP_ISO8601:timestamp}  %{WORD:level} %{NUMBER:number} --- \[%{DATA:service}\] \[     %{DATA:tread}\] \[%{DATA:trace}\] %{DATA:class} %{GREEDYDATA:log}", "%{TIMESTAMP_ISO8601:timestamp}  %{WORD:level} %{NUMBER:number} --- \[%{DATA:service}\] \[%{DATA:tread}\] \[%{DATA:trace}\] %{DATA:class} %{GREEDYDATA:log}"] }
          break_on_match => false
        }
        if ![trace] {
          drop {}
        }
        mutate {
          gsub => ["trace", "-", " "]
        }
        grok {
          match => { "trace" => "%{DATA:traceid} %{GREEDYDATA:spanid}" }
        }
      prune {
        whitelist_names => ["log", "timestamp", "level", "traceid", "service", "spanid"]
        }
      }
      output {
        elasticsearch {
          hosts => ["http://host.docker.internal:9200"]          
          index => "bank3-logs-%{+YYYY.MM.dd}"
        }
      }