
# Configuration for the customer-db (PostgreSQL dependency)
# Values here are prefixed according to the Bitnami PostgreSQL chart's structure
# Check the Bitnami chart's values.yaml for all available options
account-db:
  enabled: true
  # Override values from the official postgresql chart
  auth:
    database: market1
    username: user1
    # Use existingSecret or provide password (less secure for production)
    # existingSecret: "{{ .Release.Name }}-customer-db-postgresql" # Name of the secret to use/create
    postgresPassword: "v0IZuTHY0Y"
    password: "v0IZuTHY0Y"
    user1Password: "v0IZuTHY0Y"
     # Example: Not recommended for production TTmjMBP1wK ESUYIvEKwGz8ukwVAfYix0Ye
  primary:
    persistence:
      enabled: true
      size: 1Gi # Small size for example
account-app:
  enabled: true
  database:
    url: r2dbc:postgresql://{{ .Release.Name }}-account-db:5432/market1
    username: user1
    password: v0IZuTHY0Y
  account_secret: A8U5u54LT3m9Besj3SV39L2E6iBh4lkU
  service_url:
    notification_url: http://{{ .Release.Name }}-notification-app:8086
    keycloak_url: http://{{ .Release.Name }}-keycloak-app-http:80/auth/realms/bank-realm
  envFrom:
    - configMapRef:
        name: my-configmap

keycloak-app:
  enabled: true
# kubectl create secret generic realm-secret --from-file=realm-export.json
  command:
    - "/opt/keycloak/bin/kc.sh"
    - "start"
    - "--http-port=8080"
    - "--hostname-strict=false"
    - "--import-realm"
  extraVolumes: |
    - name: realm-secret
      secret:
        secretName: realm-secret
  extraVolumeMounts: |
    - name: realm-secret
      mountPath: "/opt/keycloak/data/import/"
      readOnly: true
  extraEnv: |
    - name: KEYCLOAK_ADMIN
      value: admin
    - name: KEYCLOAK_ADMIN_PASSWORD
      value: admin    
    - name: JAVA_OPTS_APPEND
      value: >-
        -Djgroups.dns.query={{ include "keycloak.fullname" . }}-headless
  service:
    type: LoadBalancer
    port: 8080


  

front-app:
  enabled: true
  image:
    repository: my-bank-front-app
    pullPolicy: IfNotPresent
    tag: "1.4"
  service_url:
    gateway_host: http://{{ .Release.Name }}-gateway-app:8081
    keycloak_url: http://{{ .Release.Name }}-keycloak-app-http:80/auth/realms/bank-realm
  envFrom:
    - configMapRef:
        name: front-configmap
  service:
    type: LoadBalancer
    port: 8084

gateway-app:
  enabled: true
  image:
    repository: my-bank-gateway-app
    pullPolicy: IfNotPresent
    tag: "1.3"
  service_url:
    keycloak_url: http://{{ .Release.Name }}-keycloak-app-http:80/auth/realms/bank-realm
    account_url: http://{{ .Release.Name }}-account-app:8082
    cash_url: http://{{ .Release.Name }}-cash-app:8083
    transfer_url: http://{{ .Release.Name }}-transfer-app:8085
  envFrom:
    - configMapRef:
        name: gateway-configmap