server:
  port: 8081

spring:
  application:
    name: my-bank-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${bank.keycloak-url}/protocol/openid-connect/certs
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: account-service
              uri: ${ACCOUNT.HOST:http://localhost:8082}
              predicates:
                - Path=/account/**
              filters:
                - name: JwtTokenRelay
            - id: cash-service
              uri: ${CASH.URL:http://localhost:8083}
              predicates:
                - Path=/cash/**
              filters:
                - name: JwtTokenRelay
            - id: transfer-service
              uri: ${TRANSFER.URL:http://localhost:8085}
              predicates:
                 - Path=/transfer/**
              filters:
                - name: JwtTokenRelay
management:
  endpoints:
    web:
      exposure:
        include: "*"
  zipkin:
    tracing:
      endpoint: ${ZIPKIN.URL:http://localhost:9411/api/v2/spans}
  tracing:
    sampling:
      probability: 1

logging:
  level:
    root: INFO
    org:
      springframework:
        security: trace
bank:
  keycloak-url: "${KEYCLOAK.URL:http://localhost:8080/realms/bank-realm}"